### ISSUE TITLE
RuntimeError: splatting.cuda is not available

### ISSUE THREAD

**Issue by RafailFridman** [hperrot/splatting#2]
When trying to use this with tensors on the GPU I get this:
`RuntimeError: splatting.cuda is not available`

I installed using `pip install -e .`.
Could you please help me?

**Comment by hperrot** [comment]
Hi Rafail,

probably, your include path for cuda was not found.

You could try adapting this line in the setup.py accordingly.
https://github.com/hperrot/splatting/blob/615066f8bc3be483035e6c4886cb7c0142654c27/setup.py#L15

You could also try, if the adaptions in the fork of of @pesser fix your problem:
https://github.com/pesser/splatting

I hope this helps you. 

Hannes

**Comment by yashkant** [comment]
If it helps, I was using splatting inside a directory, and needed to change 
```
    from splatting import cpu as splatting_cpu
```
to:
```
    from splatting.splatting import cpu as splatting_cpu
```
in splatting.py file.

**Comment by kobeshegu** [comment]
> 

This solved my proplem, THX.)
